FROM node:14

EXPOSE 9000

WORKDIR /root/demo_project/socialE

COPY ./package.json .

RUN npm i --legacy-peer-deps

COPY . .

# RUN npm run build

# ENTRYPOINT ["serve", "-s", "-p", "9000" , "build"]
