export const modelRegister = {
    OPENREGISTER: "OPENREGISTER",
    CLOSEREGISTER: "CLOSEREGISTER",
    OPENFORGETPASSWORD: "OPENFORGETPASSWORD",
    CLOSEFORGETPASSWORD: "CLOSEFORGETPASSWORD",
}


export const headerTooltip = {
    OPENTOOLTIP: "OPENTOOLTIP",
    CLOSETOOLTIP : "CLOSETOOLTIP"
}