export const modelRegister = {
    OPENREGISTER: "OPENREGISTER",
    CLOSEREGISTER: "CLOSEREGISTER",
    OPENFORGETPASSWORD: "OPENFORGETPASSWORD",
    CLOSEFORGETPASSWORD: "CLOSEFORGETPASSWORD",
}


export const headerTooltip = {
    OPENTOOLTIP: "OPENTOOLTIP",
    CLOSETOOLTIP : "CLOSETOOLTIP"
}


export const sidebar = {
    OPENSIDEBAR: "OPENSIDEBAR",
    CLOSESIDEBAR : "CLOSESIDEBAR"
}

export const sidebarActive = {
    HOME: "HOME",
    TEMPLATE: "TEMPLATE",
    LOGS: "LOGS",
    TARGETINFO: "TARGETINFO",
    USERMANAGEMENT: "USERMANAGEMENT"
}

export const LOGINACTIVITY = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT"
}