export const modelRegister = {
    OPENREGISTER: "OPENREGISTER",
    CLOSEREGISTER: "CLOSEREGISTER",
    OPENFORGETPASSWORD: "OPENFORGETPASSWORD",
    CLOSEFORGETPASSWORD: "CLOSEFORGETPASSWORD",
}


export const headerTooltip = {
    OPENTOOLTIP: "OPENTOOLTIP",
    CLOSETOOLTIP : "CLOSETOOLTIP"
}


export const sidebar = {
    OPENSIDEBAR: "OPENSIDEBAR",
    CLOSESIDEBAR : "CLOSESIDEBAR"
}

export const sidebarActive = {
    HOME: "HOME",
    TEMPLATE: "TEMPLATE",
    LOGS: "LOGS",
    TARGETINFO: "TARGETINFO",
    USERMANAGEMENT: "USERMANAGEMENT",
    SETTING: "SETTING",
    USERPROFILE: "USERPROFILE",
}

export const LOGINACTIVITY = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT"
}

export const token = {
    TOKEN: "TOKEN"
}

export const TEMPLATE = {
    GETTEMPLATE: "GETTEMPLATE",
    SETTEMPLATE: "SETTEMPLATE"
}


export const TEMPLATEPAGE = {
    TEMPLATECREATE: "TEMPLATECREATE",
    TEMPLATEVIEW: "TEMPLATEVIEW"
}

export const SHOWNEWTEMPLATE = {
    NEWTEMPLATE:"NEWTEMPLATE"
}


export const TargetAudience = {
    AVAILABLEAUDIENCE: "AVAILABLEAUDIENCE",
    NEWAUDIENCE: "NEWAUDIENCE",
    CLICKAUDIENCE: "CLICKAUDIENCE",
    DISABLEAUDIENCE: "DISABLEAUDIENCE",
    ADDNEWAUDIENCE:"ADDNEWAUDIENCE",
}